"""SSL certificate management via Let's Encrypt certbot."""

import asyncio
import logging
import re
import subprocess
from contextlib import suppress
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

from . import database as db

logger = logging.getLogger(__name__)

# Paths - these match the docker-compose volume mounts
LETSENCRYPT_DIR = Path("/etc/letsencrypt")
NGINX_CONF_DIR = Path("/app/nginx-conf")
CERTBOT_WEBROOT = Path("/var/www/certbot")


async def _communicate_with_timeout(proc, timeout: float):
    """Await subprocess communicate safely and cleanly on timeout."""
    task = asyncio.create_task(proc.communicate())
    try:
        return await asyncio.wait_for(task, timeout=timeout)
    except asyncio.TimeoutError:
        task.cancel()
        with suppress(asyncio.CancelledError):
            await task
        raise


async def _kill_process(proc):
    """Terminate a subprocess, supporting both sync and async mock methods."""
    with suppress(Exception):
        result = proc.kill()
        if asyncio.iscoroutine(result):
            await result


def _validate_domain(domain: str) -> bool:
    """Validate domain name per RFC 1123."""
    if not domain or len(domain) > 253:
        return False
    if "." not in domain:
        return False
    labels = domain.rstrip(".").split(".")
    for label in labels:
        if not label or len(label) > 63:
            return False
        if label.startswith("-") or label.endswith("-"):
            return False
        if not re.match(r'^[a-zA-Z0-9-]+$', label):
            return False
    return True


def get_ssl_status() -> dict:
    """Get current SSL/certificate status."""
    settings = db.get_all_settings()

    enabled = settings.get("ssl_enabled") == "true"
    domain = settings.get("ssl_domain", "")

    status = {
        "enabled": enabled,
        "domain": domain,
        "email": settings.get("ssl_email", ""),
        "expires": settings.get("ssl_cert_expires", ""),
        "using_letsencrypt": False,
        "cert_exists": False,
        "days_until_expiry": None,
        "needs_renewal": False,
    }

    if enabled and domain:
        # Check if Let's Encrypt cert exists
        cert_path = LETSENCRYPT_DIR / "live" / domain / "fullchain.pem"
        status["cert_exists"] = cert_path.exists()
        status["using_letsencrypt"] = cert_path.exists()

        # Calculate days until expiry
        expires = settings.get("ssl_cert_expires")
        if expires:
            try:
                exp_dt = datetime.fromisoformat(expires)
                days_left = (exp_dt - datetime.now()).days
                status["days_until_expiry"] = days_left
                status["needs_renewal"] = days_left < 30
            except ValueError:
                pass

    return status


def _get_cert_expiry(domain: str) -> Optional[datetime]:
    """Get certificate expiration date using openssl."""
    cert_path = LETSENCRYPT_DIR / "live" / domain / "cert.pem"
    if not cert_path.exists():
        return None

    try:
        # Use openssl to get expiry date
        result = subprocess.run(
            ["openssl", "x509", "-enddate", "-noout", "-in", str(cert_path)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            # Output looks like: notAfter=Mar 15 12:00:00 2025 GMT
            line = result.stdout.strip()
            if "=" in line:
                date_str = line.split("=", 1)[1]
                # Parse the date
                return datetime.strptime(date_str, "%b %d %H:%M:%S %Y %Z")
    except Exception as e:
        logger.warning(f"Could not read certificate expiry: {e}")

    return None


def _generate_letsencrypt_nginx_config(domain: str) -> str:
    """Generate nginx config for Let's Encrypt certificate."""
    return f"""# Let's Encrypt HTTPS configuration for {domain}
# Auto-generated by ssl_manager.py

server {{
    listen 80;
    server_name {domain};

    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000" always;

    # WebSocket support
    location /ws {{
        proxy_pass http://tachyon-mgmt:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
    }}

    # Main application
    location / {{
        proxy_pass http://tachyon-mgmt:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 500M;
    }}
}}
"""


def _write_nginx_config(domain: str):
    """Write the Let's Encrypt nginx config."""
    config = _generate_letsencrypt_nginx_config(domain)
    config_path = NGINX_CONF_DIR / "default.conf"
    config_path.write_text(config)
    logger.info(f"Wrote nginx config for {domain}")


def _reload_nginx():
    """Signal nginx to reload configuration."""
    try:
        # Try docker exec first (when running in docker-compose)
        result = subprocess.run(
            ["docker", "exec", "tachyon-nginx", "nginx", "-s", "reload"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("Nginx reloaded successfully")
            return True

        # Fallback: try direct nginx reload (if running on host)
        result = subprocess.run(
            ["nginx", "-s", "reload"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("Nginx reloaded successfully (direct)")
            return True

        logger.warning(f"Could not reload nginx: {result.stderr}")
        return False
    except Exception as e:
        logger.warning(f"Could not reload nginx: {e}")
        return False


async def obtain_certificate(domain: str, email: str) -> Tuple[bool, str]:
    """Obtain a Let's Encrypt certificate using webroot authentication.

    Returns (success, message).
    """
    if not domain:
        return False, "Domain is required"
    if not email:
        return False, "Email is required"

    # Validate domain format (RFC 1123)
    if not _validate_domain(domain):
        return False, "Invalid domain format. Must be a valid hostname (e.g., firmware.example.com)"

    logger.info(f"Requesting certificate for {domain}")

    # Verify certbot container is running before attempting certificate request
    try:
        check = await asyncio.create_subprocess_exec(
            "docker", "inspect", "--format", "{{.State.Running}}", "tachyon-certbot",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        stdout_check, _ = await _communicate_with_timeout(check, timeout=10)
        if check.returncode != 0 or stdout_check.decode().strip() != "true":
            return False, (
                "Let's Encrypt is not available: the certbot container is not running. "
                "This feature requires the Tachyon appliance deployment."
            )
    except Exception:
        return False, "Unable to check certbot container status."

    # Run certbot in webroot mode via docker exec (certbot runs in separate container)
    cmd = [
        "docker", "exec", "tachyon-certbot",
        "certbot", "certonly",
        "--webroot",
        "--webroot-path", "/var/www/certbot",
        "-d", domain,
        "--email", email,
        "--agree-tos",
        "--non-interactive",
        "--keep-until-expiring",
    ]

    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await _communicate_with_timeout(proc, timeout=120)

        output = stdout.decode() + stderr.decode()

        if proc.returncode == 0:
            logger.info(f"Certificate obtained for {domain}")

            # Get expiration date
            expiry = _get_cert_expiry(domain)
            expiry_str = expiry.isoformat() if expiry else ""

            # Update nginx config to use the new cert
            _write_nginx_config(domain)
            _reload_nginx()

            # Store in database
            db.set_setting("ssl_enabled", "true")
            db.set_setting("ssl_domain", domain)
            db.set_setting("ssl_email", email)
            db.set_setting("ssl_cert_expires", expiry_str)

            return True, "Certificate obtained successfully"
        else:
            logger.error(f"Certbot failed: {output}")
            # Extract useful error message
            if "DNS problem" in output or "NXDOMAIN" in output:
                return False, f"DNS error: {domain} does not point to this server"
            if "Connection refused" in output:
                return False, "Connection refused - ensure port 80 is accessible from the internet"
            if "too many requests" in output.lower():
                return False, "Rate limited by Let's Encrypt - try again later"
            return False, f"Certificate request failed: {output[:300]}"

    except asyncio.TimeoutError:
        if proc is not None:
            await _kill_process(proc)
        return False, "Certificate request timed out (120s)"
    except FileNotFoundError:
        return False, "docker not found - cannot reach certbot container"
    except Exception as e:
        logger.exception(f"Certificate request error: {e}")
        return False, str(e)


async def renew_certificate() -> Tuple[bool, str]:
    """Renew the current certificate.

    Returns (success, message).
    """
    settings = db.get_all_settings()
    domain = settings.get("ssl_domain")

    if not domain:
        return False, "No domain configured"

    logger.info(f"Renewing certificate for {domain}")

    cmd = ["docker", "exec", "tachyon-certbot", "certbot", "renew", "--non-interactive"]

    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await _communicate_with_timeout(proc, timeout=120)

        output = stdout.decode() + stderr.decode()

        if proc.returncode == 0:
            # Update expiry date
            expiry = _get_cert_expiry(domain)
            if expiry:
                db.set_setting("ssl_cert_expires", expiry.isoformat())

            _reload_nginx()
            logger.info(f"Certificate renewed for {domain}")
            return True, "Certificate renewed successfully"
        else:
            logger.error(f"Certbot renewal failed: {output}")
            return False, f"Renewal failed: {output[:200]}"

    except asyncio.TimeoutError:
        if proc is not None:
            await _kill_process(proc)
        return False, "Renewal timed out"
    except Exception as e:
        logger.exception(f"Renewal error: {e}")
        return False, str(e)
